
CREATE TABLE ingresos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ingreso DECIMAL(5,2) NOT NULL,
    dia CHAR(25) NOT NULL,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE motivos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    motivo TEXT NOT NULL,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gastos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ingreso_id BIGINT UNSIGNED NOT NULL,
    gasto DECIMAL(5,2) NOT NULL,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (ingreso_id) REFERENCES ingresos(id) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gastos_motivos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    gasto_id BIGINT UNSIGNED NOT NULL,
    motivo_id BIGINT UNSIGNED NOT NULL,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (gasto_id) REFERENCES gastos(id) ON DELETE CASCADE,
    FOREIGN KEY (motivo_id) REFERENCES motivos(id) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;








































CREATE TABLE clientes (
    cliente_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(45) DEFAULT NULL,
    apellido VARCHAR(45) DEFAULT NULL,
    direccion POINT  DEFAULT NULL,
    numeroDeTelefono CHAR(25) UNIQUE DEFAULT NULL,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE abonos (
    abono_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente_id BIGINT UNSIGNED NOT NULL,
    tipo ENUM('primer_abono', 'segundo_abono') NOT NULL,
    monto DECIMAL(10,2) NOT NULL DEFAULT '0.00',
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_cliente_abonos FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE saldos (
    cliente_id BIGINT UNSIGNED PRIMARY KEY,
    saldoTotal DECIMAL(10,2) NOT NULL,
    comentarios TEXT DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    primerRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimoRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_cliente_saldos FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE clientes_activos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cliente_id BIGINT UNSIGNED NOT NULL,
    primeraActualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    segundaActualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_cliente_activo FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;